[phases.setup]
nixPkgs = [
    "(php.withExtensions (pe: pe.enabled ++ []))",
    "nginx",
    "libmysqlclient",
    "phpPackages.composer",
    "nodejs_18",
]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx /var/cache/nginx",
    "composer install --no-dev --optimize-autoloader --no-interaction",
]

[phases.build]
cmds = ["php artisan package:discover --ansi"]
